[[redirects]]
  from = "/faq"
  to = "/faq/"
  status = 301

[[redirects]]
  from = "/politique-confidentialite"
  to = "/politique-confidentialite/"
  status = 301

[[redirects]]
  from = "/mentions-legales"
  to = "/mentions-legales/"
  status = 301

[[redirects]]
  from = "/accessibilite"
  to = "/accessibilite/"
  status = 301

[[redirects]]
  from = "/sos-lumbago"
  to = "/sos-lumbago/"
  status = 301

[[redirects]]
  from = "/approche"
  to = "/approche/"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/equipe"
  to = "/equipe/"
  status = 301

[[redirects]]
  from = "/suivi"
  to = "/suivi/"
  status = 301
